set -g default-terminal "screen-256color"
set -g status-style bg="#191919",fg="#B3B3B3"
set -g window-status-current-style bg=default,fg="#E6B450",bold
set -g status-justify centre
set -g status-left ""
set -g status-right ""
