format = """$directory$git_branch$git_status$cmd_duration$character"""
add_newline = true

[directory]
truncation_length = 10
truncate_to_repo = false
style = "underline bold yellow"
format = "[$path/]($style)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[git_status]
style = "red"
format = '([\[$all_status$ahead_behind\]]($style))'

[git_branch]
symbol = ""
style = "purple"
format = "[$symbol$branch]($style)"

[hostname]
ssh_only = true
format = "[$hostname]($style)"

[cmd_duration]
disabled = true

[git_commit]
format = "[ $hash$tag]($style) "
