return {
    { "voldikss/vim-floaterm" },
    { "nvim-lua/plenary.nvim" },
    { "lukas-reineke/indent-blankline.nvim", main = "ibl", opts = { indent = { char = "│" } } },
    { "NvChad/nvim-colorizer.lua", opts = { user_default_options = { names = false } } },
    { "nvim-tree/nvim-web-devicons", opts = {} },
    { "windwp/nvim-autopairs", event = "InsertEnter", opts = {} },
    { "numToStr/Comment.nvim", opts = {} },
    { "kylechui/nvim-surround", version = "*", event = "VeryLazy", opts = {} },
    { "lewis6991/gitsigns.nvim", opts = {} },
    { "echasnovski/mini.move", version = false, opts = {} },
    { "mbbill/undotree" },
    { "folke/persistence.nvim", event = "BufReadPre", opts = {} },
    { "HiPhish/rainbow-delimiters.nvim" },
    { 'mrcjkb/rustaceanvim', lazy = false, },
}
