[colors.primary]
background = "#000000"
[selection]
save_to_clipboard = true
[window]
dynamic_padding = true
opacity = 0.9

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"
[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
[[keyboard.bindings]]
key = "Space"
mods = "Control"
action = "ToggleViMode"

[font]
size = 16
[font.normal]
family = "JetBrainsMono NerdFont"
style = "Regular"
[font.italic]
family = "JetBrainsMono NerdFont"
style = "Italic"
[font.bold]
family = "JetBrainsMono NerdFont"
style = "Bold"
[font.bold_italic]
family = "JetBrainsMono NerdFont"
style = "Bold Italic"
