[colors.primary]
background = '#000000'
[colors.selection]
text   = '#c0caf5'
background = '#28344a'
[selection]
save_to_clipboard = true
[window]
dynamic_padding = true
opacity = 0.9

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"
[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
[[keyboard.bindings]]
key = "Space"
mods = "Control"
action = "ToggleViMode"

[font]
size = 16
[font.normal]
family = "JetBrainsMono NerdFont"
style = "Regular"
[font.italic]
family = "JetBrainsMono NerdFont"
style = "Italic"
[font.bold]
family = "JetBrainsMono NerdFont"
style = "Bold"
[font.bold_italic]
family = "JetBrainsMono NerdFont"
style = "Bold Italic"

[colors.bright]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"
