[bar]
order = [ "AkshitBar" ]

    [bar.AkshitBar]
    enabled = true
    auto_hide = false
    reserve_space = true
    background_opacity = 0.88
    border = "outline"
    border_width = 0.0
    capsule = false
    capsule_border_width = 1.0
    capsule_fill = "surface_variant"
    capsule_group = []
    capsule_opacity = 1.0
    capsule_padding = 6.0
    capsule_radius = 8.0
    capsule_thickness = 1.0
    center = [ "clock" ]
    compositor_blur = false
    concave_edge_corners = false
    contact_shadow = false
    end = [ "network", "bluetooth", "volume", "brightness", "battery", "session" ]
    font_family = "JetBrainsMono Nerd Font Propo"
    font_scale = 1.0
    font_weight = 400
    hover_highlight = true
    layer = "top"
    margin_edge = 0
    margin_ends = 0
    margin_opposite_edge = 0
    padding = 6
    panel_overlap = 0
    position = "top"
    radius = 0
    radius_bottom_left = 0
    radius_bottom_right = 0
    radius_top_left = 0
    radius_top_right = 0
    scale = 1.2000000476837158
    shadow = false
    show_on_workspace_switch = false
    smart_auto_hide = false
    start = [ "workspaces", "active_window" ]
    thickness = 29
    widget_spacing = 15

        [bar.AkshitBar.dead_zone.actions]
        left = "notification-clear-active"
        scroll_down = "volume-down"
        scroll_up = "volume-up"


[widget.workspaces]
hide_when_empty = true
labels_only_when_occupied = true
type = "workspaces"

[widget.active_window]
display = "icon_only"
icon_size = 14.0
max_length = 80
min_length = 0
scale = 1.5
title_scroll = "none"
type = "active_window"

[widget.battery]
show_label = false
type = "battery"

[widget.bluetooth]
show_label = true
type = "bluetooth"

[widget.brightness]
show_label = false
type = "brightness"

[widget.clock]
format = "{:%a %d %b, %H:%M}"
type = "clock"

[widget.session]
icon_color = "error"
type = "session"

[widget.volume]
show_label = false
type = "volume"
