[plugin_settings]

[plugins]
auto_update = "all"
enabled = [ "noctalia/timer" ]

    [[plugins.source]]
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"
