[plugin_settings]

[plugins]
enabled = [ "noctalia/timer", "me/stopwatch" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "/home/akshit/dev/my-plugins"
    name = "my-dev"
